// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmO_xgjfmPwUMZS2JfyTLsvgsxX0SvR3k',
    appId: '1:603952688918:web:3df7da4e136645682b2a37',
    messagingSenderId: '603952688918',
    projectId: 'riverpod-b11b5',
    authDomain: 'riverpod-b11b5.firebaseapp.com',
    storageBucket: 'riverpod-b11b5.firebasestorage.app',
    measurementId: 'G-4EVK9587ZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSFWOCczsqIRBFAAl-1Og7h7zOTFyIXjA',
    appId: '1:603952688918:android:80ee60316cff87be2b2a37',
    messagingSenderId: '603952688918',
    projectId: 'riverpod-b11b5',
    storageBucket: 'riverpod-b11b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFe6N18qFVN2pJIbEXGxUW_Izepd-Viqs',
    appId: '1:603952688918:ios:2e2afd56ee073e9b2b2a37',
    messagingSenderId: '603952688918',
    projectId: 'riverpod-b11b5',
    storageBucket: 'riverpod-b11b5.firebasestorage.app',
    iosBundleId: 'com.example.day21StateManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmO_xgjfmPwUMZS2JfyTLsvgsxX0SvR3k',
    appId: '1:603952688918:web:6f2f4ff1751367982b2a37',
    messagingSenderId: '603952688918',
    projectId: 'riverpod-b11b5',
    authDomain: 'riverpod-b11b5.firebaseapp.com',
    storageBucket: 'riverpod-b11b5.firebasestorage.app',
    measurementId: 'G-M7QFTSWQ76',
  );
}
